import { DataLayer } from "./layers/DataLayer";
import { LabelLayer } from "./layers/LabelLayer";
import { LayerRegistry } from "./layers/LayerRegistry";
import { TransformLayer } from "./layers/TransformLayer";
import { GroundLayer } from "./layers/GroundLayer";
import { ImageLayer } from "./layers/ImageLayer";
import { GltfLayer } from "./layers/GltfLayer";
import { GridMapLayer } from "./layers/GridMapLayer";
import { GeometryLayer } from "./layers/GeometryLayer";
import { PointCloudLayer } from "./layers/PointCloudLayer";
import { VideoLayer } from "./layers/VideoLayer";
import { DeviceVisualUrdfLayer } from "./layers/DeviceVisualUrdfLayer";
import { DeviceVisualTFLayer } from "./layers/DeviceVisualTFLayer";
import { EmptyLayer } from "./layers/EmptyLayer";
import { ChartLayer } from "./layers/ChartLayer";
import { MapLayer } from "./layers/MapLayer";
import { DeviceDotLayer } from "./layers/DeviceDotLayer";
// import { TrailLayer } from './layers/TrailLayer';

export * from "./components/Universe";
export * from "./layers/LayerRegistry";
export * from "./layers/UniverseLayer";
export * from "./layers/TransformLayer";
export * from "./components/sidebar";
export * from "./model/SceneGraph";
export * from "./objects/Label";
export * from "./objects/TextPlane";
export * from "./objects/ImagePlane";
export * from "./objects/Urdf";
export * from "./objects/Model3D";
export * from "./components/viewer/Hand";
export * from "./components/viewer/Controller";
export * from "./components/viewer/HandheldController";
export * from "./formantColor";
export * from "./oculusQuest";
export * from "./model/PositioningBuilder";
export * from "./model/SceneGraphBuilder";

export { defined, definedAndNotNull } from "./common/defined";

LayerRegistry.register(DataLayer);
LayerRegistry.register(LabelLayer);
LayerRegistry.register(TransformLayer);
LayerRegistry.register(GroundLayer);
LayerRegistry.register(ImageLayer);
LayerRegistry.register(GltfLayer);
LayerRegistry.register(GroundLayer);
LayerRegistry.register(GridMapLayer);
LayerRegistry.register(GeometryLayer);
LayerRegistry.register(PointCloudLayer);
LayerRegistry.register(DeviceVisualUrdfLayer);
LayerRegistry.register(DeviceVisualTFLayer);
LayerRegistry.register(VideoLayer);
LayerRegistry.register(EmptyLayer);
LayerRegistry.register(ChartLayer);
LayerRegistry.register(MapLayer);
LayerRegistry.register(DeviceDotLayer);
// LayerRegistry.register(TrailLayer);
